let contentItems=[];let currentEditId=null;let currentFilter="all";
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentFilter=b.dataset.filter;render()});document.getElementById("searchContent").oninput=render;document.getElementById("sortContent").onchange=render;loadContent()});
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open("BeyondDatabase",4);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains("videos"))d.createObjectStore("videos",{keyPath:"id",autoIncrement:true});if(!d.objectStoreNames.contains("comments"))d.createObjectStore("comments",{keyPath:"id",autoIncrement:true});if(!d.objectStoreNames.contains("likes"))d.createObjectStore("likes",{keyPath:"key"});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function loadContent(){try{const db=await openDB();const user=localStorage.getItem("beyondUsername");const videos=await getAll(db,"videos");contentItems=videos.filter(v=>!user||v.username===user);const likes=await getAll(db,"likes");const comments=await getAll(db,"comments");contentItems.forEach(v=>{v.likeCount=likes.filter(l=>l.postId===v.id).length;v.commentCount=comments.filter(c=>c.postId===v.id).length;v.views=Number(localStorage.getItem("beyondViews_"+v.id)||0);v.status=v.status||"published"});document.getElementById("totalVideos").textContent=contentItems.length;document.getElementById("totalViews").textContent=compact(contentItems.reduce((n,v)=>n+v.views,0));document.getElementById("totalLikes").textContent=compact(contentItems.reduce((n,v)=>n+v.likeCount,0));document.getElementById("totalComments").textContent=compact(contentItems.reduce((n,v)=>n+v.commentCount,0));render()}catch(e){console.error(e)}}
function getAll(db,name){return new Promise((resolve,reject)=>{const r=db.transaction(name,"readonly").objectStore(name).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function compact(n){return n>999?((n/1000).toFixed(n>9999?0:1)+"K"):String(n)}
function render(){const list=document.getElementById("contentList"),empty=document.getElementById("emptyState"),q=document.getElementById("searchContent").value.trim().toLowerCase(),sort=document.getElementById("sortContent").value;let items=contentItems.filter(v=>(currentFilter==="all"||v.status===currentFilter)&&((v.caption||"").toLowerCase().includes(q)||(v.hashtags||"").toLowerCase().includes(q)));items.sort((a,b)=>sort==="oldest"?new Date(a.createdAt)-new Date(b.createdAt):sort==="likes"?b.likeCount-a.likeCount:new Date(b.createdAt)-new Date(a.createdAt));list.innerHTML="";empty.style.display=items.length?"none":"block";items.forEach(v=>{const row=document.createElement("article");row.className="content-row";const thumb=document.createElement("video");thumb.className="thumb";if(v.video)thumb.src=URL.createObjectURL(v.video);thumb.muted=true;thumb.preload="metadata";const info=document.createElement("div");info.className="content-info";const h=document.createElement("h3");h.textContent=v.caption||"Untitled Beyond video";const p=document.createElement("p");p.textContent=v.hashtags||"No hashtags";const meta=document.createElement("div");meta.className="meta";meta.innerHTML="👁 "+v.views+" &nbsp; ❤️ "+v.likeCount+" &nbsp; 💬 "+v.commentCount+" &nbsp; • "+new Date(v.createdAt).toLocaleDateString();info.append(h,p,meta);const actions=document.createElement("div");actions.className="actions";actions.innerHTML='<button>Edit</button><button>Hide</button><button class="delete">Delete</button>';actions.children[0].onclick=()=>openEditor(v.id);actions.children[1].onclick=()=>toggleStatus(v.id);actions.children[2].onclick=()=>deleteVideo(v.id);row.append(thumb,info,actions);list.append(row)})}
function openEditor(id){const v=contentItems.find(x=>x.id===id);if(!v)return;currentEditId=id;document.getElementById("editCaption").value=v.caption||"";document.getElementById("editHashtags").value=v.hashtags||"";document.getElementById("editModal").classList.add("show")}
function closeEditor(){document.getElementById("editModal").classList.remove("show");currentEditId=null}
async function saveEditor(){const db=await openDB();const v=contentItems.find(x=>x.id===currentEditId);if(!v)return;v.caption=document.getElementById("editCaption").value.trim();v.hashtags=document.getElementById("editHashtags").value.trim();await new Promise((resolve,reject)=>{const tx=db.transaction("videos","readwrite");tx.objectStore("videos").put(v);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});closeEditor();loadContent()}
async function toggleStatus(id){const db=await openDB();const v=contentItems.find(x=>x.id===id);if(!v)return;v.status=v.status==="published"?"draft":"published";await new Promise((resolve,reject)=>{const tx=db.transaction("videos","readwrite");tx.objectStore("videos").put(v);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});loadContent()}
async function deleteVideo(id){if(!confirm("Delete this Beyond video? This cannot be undone."))return;const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction("videos","readwrite");tx.objectStore("videos").delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});loadContent()}
