let videos=[];let likes=[];let comments=[];const CUSTOM_KEY="beyondDashboardCustomization";const CUSTOM_DEFAULTS={density:"comfortable",columns:"2",insights:true,recent:true,remember:true,latest:false,tools:{content:true,analytics:true,live:true,audience:true,monetization:true,notifications:true,upload:true,comments:true,settings:true}};document.addEventListener("DOMContentLoaded",load);async function db(){return new Promise((ok,no)=>{const r=indexedDB.open("BeyondDatabase",4);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains("videos"))d.createObjectStore("videos",{keyPath:"id",autoIncrement:true});if(!d.objectStoreNames.contains("comments"))d.createObjectStore("comments",{keyPath:"id",autoIncrement:true});if(!d.objectStoreNames.contains("likes"))d.createObjectStore("likes",{keyPath:"key"});};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}function all(d,n){return new Promise((ok,no)=>{const r=d.transaction(n,"readonly").objectStore(n).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>no(r.error)})}async function load(){
 try{
  const client=window.beyondDB||(typeof initBeyondDatabase==="function"?initBeyondDatabase():null);
  if(client){
   const {data:{user}}=await client.auth.getUser();
   if(user){
    const {data:rows,error}=await client.from("videos").select("*").eq("user_id",user.id).order("created_at",{ascending:false});
    if(error)throw error;
    let likeRows=[],commentRows=[];
    const [lr,cr]=await Promise.all([client.from("likes").select("video_id"),client.from("comments").select("video_id")]);
    if(!lr.error)likeRows=lr.data||[];
    if(!cr.error)commentRows=cr.data||[];
    videos=(rows||[]).map(v=>({...v,id:v.id,caption:v.caption||"",createdAt:v.created_at,views:Number(v.views_count||0),likes:likeRows.filter(x=>x.video_id===v.id).length||Number(v.likes_count||0),comments:commentRows.filter(x=>x.video_id===v.id).length||Number(v.comments_count||0),status:v.status||"published"}));
    likes=[];comments=[];render();return;
   }
  }
  const d=await db(),u=localStorage.getItem("beyondUsername");
  videos=(await all(d,"videos")).filter(v=>!u||v.username===u);
  likes=await all(d,"likes");comments=await all(d,"comments");
  videos.forEach(v=>{v.likes=likes.filter(x=>x.postId===v.id).length;v.comments=comments.filter(x=>x.postId===v.id).length;v.views=Number(localStorage.getItem("beyondViews_"+v.id)||0)});
  render();
 }catch(e){console.error("Beyond Creator Studio:",e);render()}
}
function getCustomization(){const base={...CUSTOM_DEFAULTS,tools:{...CUSTOM_DEFAULTS.tools}};try{const saved=JSON.parse(localStorage.getItem(CUSTOM_KEY)||"null");return saved?{...base,...saved,tools:{...base.tools,...(saved.tools||{})}}:base}catch{return base}}function applyCustomization(){const c=getCustomization();document.body.dataset.dashboardDensity=c.density==="compact"?"compact":"comfortable";document.querySelector(".tools").style.gridTemplateColumns=c.columns==="1"?"1fr":"";document.querySelectorAll("[data-studio-tool]").forEach(el=>{const k=el.dataset.studioTool;el.style.display=k==="customization"||c.tools[k]!==false?"flex":"none"});document.getElementById("recentPanel").style.display=c.recent?"block":"none";document.getElementById("insightsPanel").style.display=c.insights?"block":"none";const grid=document.querySelector("main");grid.classList.toggle("dashboard-single-column",c.columns==="1");if(c.latest){const recent=document.getElementById("recent");recent.dataset.order="latest"}}function fmt(v){v=Number(v)||0;return v>=1e6?(v/1e6).toFixed(1)+"M":v>=1e3?(v/1e3).toFixed(1)+"K":String(Math.round(v))}function render(){const tv=videos.reduce((a,v)=>a+v.views,0),tl=videos.reduce((a,v)=>a+v.likes,0),tc=videos.reduce((a,v)=>a+v.comments,0);document.getElementById("creatorName").textContent=localStorage.getItem("beyondUsername")||"Creator";document.getElementById("videos").textContent=fmt(videos.length);document.getElementById("views").textContent=fmt(tv);document.getElementById("likes").textContent=fmt(tl);document.getElementById("comments").textContent=fmt(tc);document.getElementById("avgViews").textContent=fmt(videos.length?tv/videos.length:0);document.getElementById("engagement").textContent=(tv?((tl+tc)/tv*100).toFixed(1):"0")+"%";document.getElementById("followers").textContent=fmt(localStorage.getItem("beyondFollowers")||0);document.getElementById("published").textContent=videos.filter(v=>(v.status||"published")==="published").length;const recent=[...videos].sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0)).slice(0,5);document.getElementById("recent").innerHTML=recent.length?recent.map(v=>'<div class="video"><div><h3>'+esc(v.caption||"Untitled video")+'</h3><p>❤️ '+fmt(v.likes)+' · 💬 '+fmt(v.comments)+'</p></div><strong>👁 '+fmt(v.views)+'</strong></div>').join(""):'<p style="color:#9299a6;font-size:12px">No videos yet. Upload your first Beyond video.</p>';applyCustomization()}function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}