const BEYOND_MONETIZATION_VERSION="2.1.0";
let videos=[],db=null;document.addEventListener("DOMContentLoaded",init);function num(v){return Number(v)||0}function money(v){return num(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}async function init(){loadSettings();
  try{db=await openDB();videos=await readVideos()}catch(e){videos=[]}
  await loadRemoteVideos();
  render();
}
async function loadRemoteVideos(){
  try{
    const client=window.beyondDB;
    if(!client?.auth?.getUser)return;
    const session=await client.auth.getUser();
    const user=session?.data?.user;
    if(!user)return;
    const result=await client.from("videos").select("id,user_id,caption,status,views_count,likes_count,created_at").eq("user_id",user.id).order("created_at",{ascending:false});
    if(result.error||!Array.isArray(result.data))return;
    const remote=result.data.map(v=>({id:v.id,caption:v.caption||"Untitled video",status:v.status,views:num(v.views_count),likes:num(v.likes_count),monetizationEligible:false,monetized:false,earnings:0}));
    const localById=new Map(videos.map(v=>[String(v.id),v]));
    videos=remote.map(v=>Object.assign({},localById.get(String(v.id))||{},v));
  }catch(error){console.warn("Beyond Monetization remote video metrics unavailable:",error)}
}function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open("BeyondDatabase",4);r.onerror=()=>reject(r.error);r.onsuccess=()=>resolve(r.result);r.onupgradeneeded=()=>{}})}function readVideos(){return new Promise((resolve,reject)=>{if(!db.objectStoreNames.contains("videos"))return resolve([]);const r=db.transaction("videos","readonly").objectStore("videos").getAll();r.onsuccess=()=>resolve(Array.isArray(r.result)?r.result:[]);r.onerror=()=>reject(r.error)})}function loadSettings(){let s={};try{s=JSON.parse(localStorage.getItem("beyondMonetizationSettings")||"{}")}catch(e){}document.getElementById("monetizationEnabled").checked=!!s.enabled;document.getElementById("videoEnabled").checked=s.videoEnabled!==false;document.getElementById("giftsEnabled").checked=s.giftsEnabled!==false}function render(){const ve=num(localStorage.getItem("beyondVideoEarnings")),le=num(localStorage.getItem("beyondLiveEarnings")),g=num(localStorage.getItem("beyondLiveGifts")),eligible=videos.filter(v=>v.monetizationEligible===true||v.monetized===true),total=ve+le;document.getElementById("earnings").textContent=money(total);document.getElementById("videoEarnings").textContent=money(ve);document.getElementById("liveEarnings").textContent=money(le);document.getElementById("totalEarnings").textContent=money(total);document.getElementById("gifts").textContent=money(g);document.getElementById("eligible").textContent=eligible.length;const on=document.getElementById("monetizationEnabled").checked;document.getElementById("status").textContent=on?"Enabled":"Not enabled";document.getElementById("statusNote").textContent=on?"Local creator setting enabled":"No payout account connected";renderVideos(eligible)}function renderVideos(list){const box=document.getElementById("videos");if(!list.length){box.innerHTML='<p style="color:#9299a8;font-size:12px">No videos have recorded monetization eligibility yet.</p>';return}box.innerHTML=list.slice().reverse().map(v=>{const title=v.caption||v.title||"Untitled video",views=num(v.views||localStorage.getItem("beyondViews_"+v.id));return '<div class="video-row"><div><strong>'+esc(title)+'</strong><span>'+views.toLocaleString()+' views</span></div><span class="eligible">ELIGIBLE</span><span>'+money(v.earnings||0)+'</span></div>'}).join("")}function saveSettings(){localStorage.setItem("beyondMonetizationSettings",JSON.stringify({enabled:document.getElementById("monetizationEnabled").checked,videoEnabled:document.getElementById("videoEnabled").checked,giftsEnabled:document.getElementById("giftsEnabled").checked}));render()}