let currentPostId=null;

document.addEventListener("DOMContentLoaded",()=>{loadBeyondVideos();activateVideoObserver();updateAllFollowButtons()});

function openDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open("BeyondDatabase",1);request.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains("videos"))db.createObjectStore("videos",{keyPath:"id",autoIncrement:true})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}

async function loadBeyondVideos(){try{const db=await openDatabase();const tx=db.transaction(["videos"],"readonly");const req=tx.objectStore("videos").getAll();req.onsuccess=()=>{req.result.reverse().forEach(createVideoCard);activateVideoObserver();updateAllFollowButtons()}}catch(e){console.error(e)}}

function createVideoCard(post){const feed=document.getElementById("feed");const section=document.createElement("section");section.className="video-card";section.dataset.creator=post.username;const video=document.createElement("video");video.className="video";video.src=URL.createObjectURL(post.video);video.loop=true;video.muted=true;video.playsInline=true;const info=document.createElement("div");info.className="video-info";const row=document.createElement("div");row.className="creator-row";const name=document.createElement("h3");name.textContent="@"+post.username;const follow=document.createElement("button");follow.className="follow-button";follow.onclick=()=>toggleFollow(post.username,follow);row.append(name,follow);updateFollowButton(post.username,follow);const caption=document.createElement("p");caption.textContent=post.caption;const tags=document.createElement("p");tags.textContent=post.hashtags||"";info.append(row,caption,tags);const actions=document.createElement("div");actions.className="video-actions";actions.innerHTML='<button onclick="likeVideo(this)">❤️ <span>0</span></button><button>💬 <span>0</span></button><button onclick="shareVideo()">↗️ <span>Share</span></button><button onclick="openProfile()">👤 <span>Profile</span></button>';actions.children[1].onclick=()=>commentVideo(post.id);section.append(video,info,actions);feed.appendChild(section)}

function escapeHTML(text){const div=document.createElement("div");div.textContent=text;return div.innerHTML}

function likeVideo(button){const count=button.querySelector("span");let likes=Number(count.textContent);if(!button.classList.contains("liked")){likes++;button.classList.add("liked");button.style.color="#ff2d55"}else{likes--;button.classList.remove("liked");button.style.color="white"}count.textContent=likes}

async function shareVideo(){if(navigator.share){try{await navigator.share({title:"Beyond",text:"Check out this video on Beyond!"})}catch{}}else alert("Sharing is not supported by this browser yet.")}

function openLogin(){location.href="login.html"}function openUpload(){location.href="upload.html"}function openProfile(){location.href="profile.html"}function openSearch(){location.href="search.html"}

function getFollowing(){try{return JSON.parse(localStorage.getItem("beyondFollowing")||"[]")}catch{return[]}}
function saveFollowing(list){localStorage.setItem("beyondFollowing",JSON.stringify(list))}
function toggleFollow(username,button){const currentUser=localStorage.getItem("beyondUsername");if(!currentUser){alert("Please create a Beyond account before following creators.");location.href="login.html";return}if(currentUser===username){alert("You cannot follow yourself.");return}let following=getFollowing();const index=following.indexOf(username);if(index===-1)following.push(username);else following.splice(index,1);saveFollowing(following);updateFollowButton(username,button)}
function updateFollowButton(username,button){const following=getFollowing();const isFollowing=following.includes(username);button.textContent=isFollowing?"Following":"Follow";button.classList.toggle("following",isFollowing)}
function updateAllFollowButtons(){document.querySelectorAll(".follow-button").forEach(button=>{const row=button.closest(".creator-row");if(row){const username=row.querySelector("h3").textContent.replace("@","");updateFollowButton(username,button)}})}
function showFollowing(){const following=getFollowing();document.querySelectorAll(".video-card").forEach(card=>{card.style.display=following.includes(card.dataset.creator)?"flex":"none"});if(!following.length)alert("You are not following anyone yet. Follow a creator first!")}
function showFeed(){document.querySelectorAll(".video-card").forEach(card=>card.style.display="flex");document.getElementById("feed").scrollTo({top:0,behavior:"smooth"})}

function commentVideo(postId){currentPostId=postId;document.getElementById("commentsPanel").style.display="flex";document.getElementById("commentsOverlay").style.display="block";loadComments(postId)}
function closeComments(){document.getElementById("commentsPanel").style.display="none";document.getElementById("commentsOverlay").style.display="none";currentPostId=null}
function openCommentsDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open("BeyondDatabase",2);request.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains("videos"))db.createObjectStore("videos",{keyPath:"id",autoIncrement:true});if(!db.objectStoreNames.contains("comments"))db.createObjectStore("comments",{keyPath:"id",autoIncrement:true})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function addComment(){const input=document.getElementById("commentInput");const text=input.value.trim();if(!text||currentPostId===null)return;const username=localStorage.getItem("beyondUsername")||"BeyondUser";const db=await openCommentsDatabase();const tx=db.transaction(["comments"],"readwrite");tx.objectStore("comments").add({postId:currentPostId,username,text,createdAt:new Date().toISOString()});tx.oncomplete=()=>{input.value="";loadComments(currentPostId)}}
async function loadComments(postId){const list=document.getElementById("commentsList");list.innerHTML="<p style='color:#777'>Loading...</p>";try{const db=await openCommentsDatabase();const req=db.transaction(["comments"],"readonly).objectStore("comments").getAll();req.onsuccess=()=>{const comments=req.result.filter(c=>c.postId===postId).reverse();list.innerHTML="";if(!comments.length){list.innerHTML="<p style='color:#777;text-align:center;padding:30px'>No comments yet. Be the first!</p>";return}comments.forEach(createComment)}}catch(e){console.error(e)}}
function createComment(comment){const item=document.createElement("div");item.className="comment";const avatar=document.createElement("div");avatar.className="comment-avatar";avatar.textContent=comment.username.charAt(0).toUpperCase();const content=document.createElement("div");content.className="comment-content";const username=document.createElement("div");username.className="comment-username";username.textContent="@"+comment.username;const text=document.createElement("div");text.className="comment-text";text.textContent=comment.text;content.append(username,text);item.append(avatar,content);document.getElementById("commentsList").appendChild(item)}

function activateVideoObserver(){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{const video=entry.target;if(entry.isIntersecting)video.play().catch(()=>{});else video.pause()}),{threshold:.7});document.querySelectorAll(".video").forEach(v=>observer.observe(v))}
