const KEY="beyondSecuritySettings";const $=id=>document.getElementById(id);const defaults={rememberLogin:true,confirmSignout:true};
function prefs(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return {...defaults}}}
function savePrefs(){localStorage.setItem(KEY,JSON.stringify({rememberLogin:$("rememberLogin").checked,confirmSignout:$("confirmSignout").checked}))}
async function db(){return typeof initBeyondDatabase==="function"?initBeyondDatabase():null}
async function check(){const client=await db();if(!client){$("account").textContent="Supabase not configured";$("sessionStatus").textContent="Unavailable";$("checked").textContent=new Date().toLocaleString();return}try{const {data,error}=await client.auth.getSession();if(error)throw error;const user=data.session?.user;if(user){$("account").textContent=user.email||"Signed in";$("sessionStatus").textContent="Active"}else{$("account").textContent="Not signed in";$("sessionStatus").textContent="Expired / signed out"}}catch(e){$("account").textContent="Unavailable";$("sessionStatus").textContent="Could not verify"}$("checked").textContent=new Date().toLocaleString()}
async function signOut(){savePrefs();if($("confirmSignout").checked&&!confirm("Sign out of Beyond on this browser?"))return;if(typeof beyondLogout==="function"){await beyondLogout();return}const client=await db();if(client)await client.auth.signOut();location.replace("login.html")}
async function changePassword(){const client=await db();if(!client)return alert("Supabase is not configured.");const {data}=await client.auth.getSession();if(!data.session)return alert("Please log in again.");const next=prompt("Enter a new password (at least 6 characters):");if(next===null)return;if(next.length<6)return alert("Password must be at least 6 characters.");const confirmPassword=prompt("Confirm the new password:");if(next!==confirmPassword)return alert("Passwords do not match.");const {error}=await client.auth.updateUser({password:next});if(error)alert(error.message);else alert("Your Beyond password has been changed.")}
async function changeEmail(){const client=await db();if(!client)return alert("Supabase is not configured.");const email=prompt("Enter your new email address:");if(!email)return;const value=email.trim().toLowerCase();if(!/^\\S+@\\S+\\.\\S+$/.test(value))return alert("Enter a valid email address.");const {error}=await client.auth.updateUser({email:value});if(error)alert(error.message);else alert("A confirmation message may be sent to your email. Follow Supabase's confirmation instructions.")}
$("signOut").onclick=signOut;$("signOutTop").onclick=signOut;$("rememberLogin").onchange=savePrefs;$("confirmSignout").onchange=savePrefs;$("resetPassword").onclick=async()=>{const client=await db();const {data}=client?await client.auth.getUser():{data:{user:null}};if(!data.user)return alert("Please log in first.");const {error}=await client.auth.resetPasswordForEmail(data.user.email,{redirectTo:new URL("reset-password.html",location.href).href});if(error)alert(error.message);else alert("Password reset email sent. Check your inbox.")};
const passwordButton=document.createElement("button");passwordButton.className="secondary";passwordButton.textContent="Change password";passwordButton.onclick=changePassword;document.querySelector('.card:nth-of-type(3)')?.appendChild(passwordButton);
const emailButton=document.createElement("button");emailButton.className="secondary";emailButton.textContent="Change email";emailButton.onclick=changeEmail;document.querySelector('.card:nth-of-type(3)')?.appendChild(emailButton);
const p=prefs();$("rememberLogin").checked=!!p.rememberLogin;$("confirmSignout").checked=!!p.confirmSignout;check();