-- Beyond: baseline Supabase setup for cloud video/photo publishing and feed realtime.
-- Run in Supabase Dashboard > SQL Editor as project owner.
-- Review against any tables you already created before running. This does not create
-- every optional feature table used by Beyond (chat, live rooms, notifications, blocks).

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  bio text not null default '',
  avatar_url text,
  banner_url text,
  accent_color text not null default '#ff2d55',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  video_url text not null,
  caption text not null default '',
  hashtags text not null default '',
  status text not null default 'published' check (status in ('draft','published','private')),
  views_count bigint not null default 0 check (views_count >= 0),
  likes_count bigint not null default 0 check (likes_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id uuid not null references public.videos(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, video_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  video_id uuid not null references public.videos(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists videos_published_created_idx
  on public.videos (created_at desc) where status = 'published';
create index if not exists videos_user_created_idx on public.videos (user_id, created_at desc);
create index if not exists follows_following_idx on public.follows (following_id);
create index if not exists likes_video_idx on public.likes (video_id);
create index if not exists comments_video_created_idx on public.comments (video_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.videos enable row level security;
alter table public.follows enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;

drop policy if exists "Profiles are readable" on public.profiles;
create policy "Profiles are readable" on public.profiles for select to anon, authenticated using (true);
drop policy if exists "Users create own profile" on public.profiles;
create policy "Users create own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Published videos are readable" on public.videos;
create policy "Published videos are readable" on public.videos for select to anon, authenticated using (status = 'published' or auth.uid() = user_id);
drop policy if exists "Users create own videos" on public.videos;
create policy "Users create own videos" on public.videos for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users update own videos" on public.videos;
create policy "Users update own videos" on public.videos for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users delete own videos" on public.videos;
create policy "Users delete own videos" on public.videos for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Follows are readable" on public.follows;
create policy "Follows are readable" on public.follows for select to anon, authenticated using (true);
drop policy if exists "Users follow as themselves" on public.follows;
create policy "Users follow as themselves" on public.follows for insert to authenticated with check (auth.uid() = follower_id and follower_id <> following_id);
drop policy if exists "Users unfollow as themselves" on public.follows;
create policy "Users unfollow as themselves" on public.follows for delete to authenticated using (auth.uid() = follower_id);

drop policy if exists "Likes are readable" on public.likes;
create policy "Likes are readable" on public.likes for select to anon, authenticated using (true);
drop policy if exists "Users like as themselves" on public.likes;
create policy "Users like as themselves" on public.likes for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users remove own likes" on public.likes;
create policy "Users remove own likes" on public.likes for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Comments are readable" on public.comments;
create policy "Comments are readable" on public.comments for select to anon, authenticated using (true);
drop policy if exists "Signed in users add own comments" on public.comments;
create policy "Signed in users add own comments" on public.comments for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users delete own comments" on public.comments;
create policy "Users delete own comments" on public.comments for delete to authenticated using (auth.uid() = user_id);

-- Public read bucket for the URLs currently used by Beyond's feed.
-- If you want private videos, do not use getPublicUrl; switch the app to signed URLs.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('videos', 'videos', true, 1073741824,
  array['video/mp4','video/webm','video/quicktime','video/ogg','image/jpeg','image/png','image/webp','image/gif','image/avif'])
on conflict (id) do update set
  public = excluded.public,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Anyone can view Beyond media" on storage.objects;
create policy "Anyone can view Beyond media" on storage.objects
for select to anon, authenticated using (bucket_id = 'videos');

drop policy if exists "Users upload media to own folder" on storage.objects;
create policy "Users upload media to own folder" on storage.objects
for insert to authenticated with check (
  bucket_id = 'videos' and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users update media in own folder" on storage.objects;
create policy "Users update media in own folder" on storage.objects
for update to authenticated using (
  bucket_id = 'videos' and (storage.foldername(name))[1] = auth.uid()::text
) with check (
  bucket_id = 'videos' and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users delete media in own folder" on storage.objects;
create policy "Users delete media in own folder" on storage.objects
for delete to authenticated using (
  bucket_id = 'videos' and (storage.foldername(name))[1] = auth.uid()::text
);

-- Enable Postgres Changes for feed refreshes; safe to run more than once.
do $$
declare t text;
begin
  foreach t in array array['videos','likes','comments','follows'] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- This baseline intentionally does not create privileged RPC functions or policies
-- for messaging, live rooms, notifications, blocking, or recommendation scoring.
