-- DEPRECATED LEGACY SCHEMA — DO NOT RUN THIS FILE.
-- This older schema conflicts with the current Beyond client (notably video IDs,
-- hashtags, and content status). Use the canonical root-level supabase-setup.sql.
-- Review the target Supabase project's existing tables before applying migrations.
