
-- BEYOND: CORE SUPABASE DATABASE SETUP
-- Supports profiles, videos, follows, likes, comments, storage and realtime.
-- Review existing policies and schema before running on an existing database.

begin;

create extension if not exists pgcrypto;

-- 1. PROFILES
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  bio text not null default '',
  avatar_url text,
  banner_url text,
  accent_color text not null default '#ff2d55',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. VIDEOS
create table if not exists public.videos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  video_url text not null,
  caption text not null default '',
  hashtags text not null default '',
  status text not null default 'published'
    check (status in ('draft', 'published', 'private')),
  views_count bigint not null default 0 check (views_count >= 0),
  likes_count bigint not null default 0 check (likes_count >= 0),
  created_at timestamptz not null default now()
);

-- 3. FOLLOWS
create table if not exists public.follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

-- 4. LIKES
create table if not exists public.likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id uuid not null references public.videos(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, video_id)
);

-- 5. COMMENTS
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  video_id uuid not null references public.videos(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null
    check (char_length(trim(content)) between 1 and 1000),
  hidden_by_creator boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.comments
  add column if not exists hidden_by_creator boolean not null default false;

-- 6. INDEXES
create index if not exists videos_published_created_idx
  on public.videos (created_at desc)
  where status = 'published';

create index if not exists videos_user_created_idx
  on public.videos (user_id, created_at desc);

create index if not exists follows_following_idx
  on public.follows (following_id);

create index if not exists likes_video_idx
  on public.likes (video_id);

create index if not exists comments_video_created_idx
  on public.comments (video_id, created_at desc);

-- 7. ENABLE ROW LEVEL SECURITY
alter table public.profiles enable row level security;
alter table public.videos enable row level security;
alter table public.follows enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;

-- 8. PROFILE POLICIES
drop policy if exists "Profiles are readable" on public.profiles;
create policy "Profiles are readable"
on public.profiles for select to anon, authenticated
using (true);

drop policy if exists "Users create own profile" on public.profiles;
create policy "Users create own profile"
on public.profiles for insert to authenticated
with check (auth.uid() = id);

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile"
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- 9. VIDEO POLICIES
drop policy if exists "Published videos are readable" on public.videos;
create policy "Published videos are readable"
on public.videos for select to anon, authenticated
using (status = 'published' or auth.uid() = user_id);

drop policy if exists "Users create own videos" on public.videos;
create policy "Users create own videos"
on public.videos for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users update own videos" on public.videos;
create policy "Users update own videos"
on public.videos for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users delete own videos" on public.videos;
create policy "Users delete own videos"
on public.videos for delete to authenticated
using (auth.uid() = user_id);

-- 10. FOLLOW POLICIES
drop policy if exists "Follows are readable" on public.follows;
create policy "Follows are readable"
on public.follows for select to anon, authenticated
using (true);

drop policy if exists "Users follow as themselves" on public.follows;
create policy "Users follow as themselves"
on public.follows for insert to authenticated
with check (
  auth.uid() = follower_id
  and follower_id <> following_id
);

drop policy if exists "Users unfollow as themselves" on public.follows;
create policy "Users unfollow as themselves"
on public.follows for delete to authenticated
using (auth.uid() = follower_id);

-- 11. LIKE POLICIES
drop policy if exists "Likes are readable" on public.likes;
create policy "Likes are readable"
on public.likes for select to anon, authenticated
using (true);

drop policy if exists "Users like as themselves" on public.likes;
create policy "Users like as themselves"
on public.likes for insert to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.videos v
    where v.id = video_id
      and v.status = 'published'
  )
);

drop policy if exists "Users remove own likes" on public.likes;
create policy "Users remove own likes"
on public.likes for delete to authenticated
using (auth.uid() = user_id);

-- 12. COMMENT POLICIES
drop policy if exists "Comments are readable" on public.comments;
create policy "Comments are readable"
on public.comments for select to anon, authenticated
using (
  exists (
    select 1
    from public.videos v
    where v.id = comments.video_id
      and (
        v.status = 'published'
        or v.user_id = (select auth.uid())
      )
      and (
        comments.hidden_by_creator = false
        or v.user_id = (select auth.uid())
      )
  )
);

drop policy if exists "Signed in users add own comments" on public.comments;
create policy "Signed in users add own comments"
on public.comments for insert to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.videos v
    where v.id = video_id
      and v.status = 'published'
  )
);

drop policy if exists "Users delete own comments" on public.comments;
create policy "Users delete own comments"
on public.comments for delete to authenticated
using (auth.uid() = user_id);

-- Only the owner of the video can hide/unhide its comments.
drop policy if exists "Video owners hide comments" on public.comments;
create policy "Video owners hide comments"
on public.comments for update to authenticated
using (
  exists (
    select 1 from public.videos v
    where v.id = comments.video_id
      and v.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.videos v
    where v.id = comments.video_id
      and v.user_id = (select auth.uid())
  )
);

-- 13. SUPABASE STORAGE
-- Files must be uploaded into a folder named with the signed-in user's UUID.
insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
)
values (
  'videos',
  'videos',
  true,
  1073741824,
  array[
    'video/mp4',
    'video/webm',
    'video/quicktime',
    'video/ogg',
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/avif'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Anyone can view Beyond media" on storage.objects;
create policy "Anyone can view Beyond media"
on storage.objects for select to anon, authenticated
using (bucket_id = 'videos');

drop policy if exists "Users upload media to own folder" on storage.objects;
create policy "Users upload media to own folder"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'videos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Users update media in own folder" on storage.objects;
create policy "Users update media in own folder"
on storage.objects for update to authenticated
using (
  bucket_id = 'videos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'videos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Users delete media in own folder" on storage.objects;
create policy "Users delete media in own folder"
on storage.objects for delete to authenticated
using (
  bucket_id = 'videos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

-- 14. REALTIME
-- Adds the four core tables to Supabase Realtime if they are not present.
do $$
declare
  table_name text;
begin
  foreach table_name in array array['videos', 'likes', 'comments', 'follows']
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = table_name
    ) then
      execute format(
        'alter publication supabase_realtime add table public.%I',
        table_name
      );
    end if;
  end loop;
end $$;

-- 15. CREATE/ENSURE THE SIGNED-IN USER'S PROFILE
create or replace function public.ensure_beyond_profile(
  requested_username text,
  requested_display_name text
)
returns jsonb
language plpgsql
set search_path = ''
as $function$
declare
  current_user_id uuid := auth.uid();
  user_email text := auth.jwt() ->> 'email';
  user_metadata jsonb :=
    coalesce(auth.jwt() -> 'user_metadata', '{}'::jsonb);
  base_username text;
  safe_username text;
  chosen_display_name text;
begin
  if current_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  base_username := lower(coalesce(
    nullif(trim(requested_username), ''),
    nullif(user_metadata ->> 'username', ''),
    split_part(coalesce(user_email, 'beyond_user'), '@', 1)
  ));

  safe_username := left(
    regexp_replace(base_username, '[^a-z0-9._-]', '', 'g'),
    30
  );

  if length(safe_username) < 3 then
    safe_username := 'user_' ||
      substr(replace(current_user_id::text, '-', ''), 1, 8);
  end if;

  -- Use a stable user-specific suffix if the username is already taken.
  if exists (
    select 1
    from public.profiles p
    where p.username = safe_username
      and p.id <> current_user_id
  ) then
    safe_username := left(safe_username, 21) || '_' ||
      substr(replace(current_user_id::text, '-', ''), 1, 8);
  end if;

  chosen_display_name := coalesce(
    nullif(trim(requested_display_name), ''),
    nullif(user_metadata ->> 'display_name', ''),
    safe_username
  );

  insert into public.profiles (id, username, display_name)
  values (current_user_id, safe_username, chosen_display_name)
  on conflict (id) do update
    set username = coalesce(public.profiles.username, excluded.username),
        display_name = coalesce(
          nullif(public.profiles.display_name, ''),
          excluded.display_name
        );

  return jsonb_build_object(
    'id', current_user_id,
    'username', safe_username
  );
end;
$function$;

create or replace function public.ensure_beyond_profile()
returns jsonb
language sql
set search_path = ''
as $function$
  select public.ensure_beyond_profile(null::text, null::text);
$function$;

revoke all on function public.ensure_beyond_profile(text, text) from public;
revoke all on function public.ensure_beyond_profile() from public;

grant execute on function public.ensure_beyond_profile(text, text)
to authenticated;

grant execute on function public.ensure_beyond_profile()
to authenticated;

commit;

-- NOTE:
-- This is the CORE setup only. It does not implement chat, live rooms,
-- notifications, blocking, Creator Studio analytics, or recommendation RPCs.
-- Public Storage means anyone with a media URL can view that media.

