-- DEPRECATED DUPLICATE — DO NOT RUN THIS LEGACY FILE.
-- The canonical Beyond schema and profile-creation RPC are maintained at:
-- ../supabase-setup.sql (repository root).
-- Open that root-level file in GitHub and run it in the Supabase SQL Editor
-- only after reviewing the target project's existing schema.
